variables:
  REPO_NAME: 'vcpkg'
  VCPKG_ROOT: '$(Build.SourcesDirectory)'

jobs:
- job: Windows

  strategy:
    matrix:
      vc141:
        VM_IMAGE_NAME: 'vs2017-win2016'
        BUILD_TOOLSET_VERSION: '141'
      vc142:
        VM_IMAGE_NAME: 'windows-2019'
        BUILD_TOOLSET_VERSION: '142'

  pool:
    vmImage: $(VM_IMAGE_NAME)

  steps:
  - task: BatchScript@1
    displayName: 'Bootstrap'
    inputs:
      filename: 'bootstrap-vcpkg.bat'

  - script: $(VCPKG_ROOT)\vcpkg.exe install --triplet x64-windows-vc$(BUILD_TOOLSET_VERSION) boost-dll boost-any boost-multi-index fmt spdlog yaml-cpp assimp imgui
    displayName: 'Install for render_pipeline_cpp'

  - script: $(VCPKG_ROOT)\vcpkg.exe install --triplet x64-windows-vc$(BUILD_TOOLSET_VERSION) openvr
    displayName: 'Install for rpcpp_plugins'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(VCPKG_ROOT)/installed'
      archiveType: '7z'
      archiveFile: '$(Build.ArtifactStagingDirectory)/vcpkg-installed.7z'

  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: '$(REPO_NAME)-vc$(BUILD_TOOLSET_VERSION)'
